### PR TITLE
Added Google Chrome Beta

### PR DESCRIPTION
**Pull request by PhnxRbrn**
Added Google Chrome Beta

### CODE REVIEW

**Comment by satya164** [comment]
The pull request is not mergable.

BTW, I'm not really sure about merging this. It might confuse a novice user so as to which version of Chrome to install. Having different versions of Sublime Text, IntelliJ idea etc. are ok, coz they are targeted to advanced users, who will know which one to install.

**Comment by PhnxRbrn** [comment]
OK, that is fine.  I know there was someone asking for chrome beta in issue #180 and I was not sure how to do a selector and thought that maybe this was the next best thing.

**Comment by PhnxRbrn** [comment]
If you want me to fix this to accommodate issue #180, I can.  Otherwise, close this request.

**Comment by satya164** [comment]
@PhnxRbrn No problem. May be I could think of something in the future, like a overflow menu for things like this, which are hidden, but available for advanced users. Let's see.

Pull requests are always welcome though. There are lots of other requests. May be you can have a look if you want to contribute. Thanks.

**Pull request closed without merging**
